//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasOil.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> UnitOfMeasurementId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ProductsGroup ProductsGroup { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
    }
}
