//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCategory
    {
        public RequestCategory()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public long Id { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
