//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasurement
    {
        public UnitOfMeasurement()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
