//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserPermissions = new HashSet<UserPermission>();
        }
    
        public long Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> OffTime { get; set; }
        public long RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
    }
}
